### ISSUE TITLE
JVM dashboard example

### ISSUE THREAD

**Issue by draco1023** [openobserve/dashboards#3]
I would like to create a JVM Dashboard similar to https://grafana.com/grafana/dashboards/18812-jvm-overview-opentelemetry/, but I am unsure how some of the expressions in it can be translated into queries in OpenObserve. Could you provide an example?

**Comment by prabhatsharma** [comment]
Have you checked https://www.youtube.com/watch?v=kjUvXQdL798

**Comment by draco1023** [comment]
@prabhatsharma Great tutorial! Thanks a lot.
